apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: eric-playlist
  description: Eric from Playlist Development Team
spec:
  profile:
    displayName: Eric
    email: eric.playlist@example.com
    picture: https://avatars.dicebear.com/api/avataaars/jonathon-page@example.com.svg?background=%23fff
  memberOf: [team-playlist]
