apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sre-team
  description: Site Reliability Engineering Team
spec:
  type: team
  profile:
    displayName: SRE Team
    email: sre-team@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
    parent: backstage
  children: []
