apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: playlist-dev-team
  description: Playlist Development Team
spec:
  type: team
  profile:
    displayName: Playlist Development Team
    email: playlist-team@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-b@example.com.svg?background=%23fff&margin=25
  parent: backstage
  children: []
