apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: engineering
  description: The Engineering Group
spec:
  type: team
  profile:
    displayName: Engineering
    email: engineering@example.com
  children:
    - group:sre-team
    - group:playlist-dev-team
